Made simple FTP
Alexander-Ploskin/MathMechReposSemester3 pull request #7
Opened 2020-11-01 14:50 UTC by Alexander-Ploskin

2020-12-06 10:44 UTC, yurii-litvinov requested changes
Ещё хочется интеграционные тесты, которые показывают, что клиент и сервер реально могут общаться по сети.

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +        public async Task<(int size, IEnumerable<(string, bool)> names)> ListAsync(string path)
Возможно, результат запроса заслуживает отдельного класса

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +        private readonly StreamReader reader;
Стоило бы FTPClient сделать IDisposable, чтобы корректно закрывать читателя и писателя

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +            if (!int.TryParse(splittedResponse[0], out var size))
Если уж InvalidResponseMessage, то тут стоило бы проверить, что splittedResponse на самом деле содержит нулевой элемент

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +                    var name = splittedResponse[i];
Ну и, конечно, проверить, что в size правда написана

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +                return (size, names);
И я не уверен, что size так уж актуален для пользователя, ведь он всегда равен names.Length

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/Program.cs
> +                using (var tCPClient = new TcpClient(hostname, port))
Тут что-то с регистром произошло нехорошее :) К тому же, тут тоже можно было бы using var

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/Program.cs
> +            const string hostname = "localhost";
Это для большей универсальности стоило бы принимать как аргументы командной строки

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/UserInterface.cs
> +        private readonly FTPClient fTPClient;
Всё-таки ftpClient обычно пишут. Аббревиатура целиком пишется в том регистре букв, что и первая буква, а иногда считается отдельным словом в смысле camelCase. То есть FTPClient, ftpClient и FtpClient ок, а fTPClient не ок

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/UserInterface.cs
> +        }
Некоторый овердизайн, Console.WriteLine четыре раза было бы ничем не хуже (и, кстати, вдвое короче).

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClient/UserInterface.cs
> +            }
Можно `IntroductionMessages().ToList().ForEach(Console.WriteLine);`

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPClientTests/FTPClientTests.cs
> +            catch (Exception) { }
Стоило бы написать Assert.Throws и проверять, что бросается конкретный тип исключения. try/catch в тестах нужен только тогда, когда хочется свойства исключения проверить. Вы, конечно, можете возразить, что исключение тут --- не часть тестового сценария, но проверяя исключение мы можем найти ещё полезные ошибки, например, NullReferenceException. И главное, это показывает, что при написании теста вы точно знаете, как должна вести себя система. try/catch в этом смысле не очень, потому что выражает неуверенность, что исключение будет брошено.

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPServer/ConnectionProvider.cs
> +        TcpListener tcpListener;
private

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPServer/ConnectionProvider.cs
> +                var client = await tcpListener.AcceptTcpClientAsync();
Надо, чтобы его кто-то корректно закрыл. Стоит отдавать его в HandleRequests и там сразу брать на него using

2020-12-06 10:44 UTC, yurii-litvinov commented on 4.1/FTPServerTests/FTPRequestHandlerTests.cs
> +            Assert.AreEqual(null, response.stream);
Assert.IsNull

2020-12-06 16:34 UTC, Alexander-Ploskin commented on 4.1/FTPClient/FTPClient.cs
> +        public async Task<(int size, IEnumerable<(string, bool)> names)> ListAsync(string path)
Похоже, не заслуживает, раз size не нужен пользователю

2020-12-06 18:12 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +        public async Task<(int size, IEnumerable<(string, bool)> names)> ListAsync(string path)
Тогда не надо :)

2020-12-11 17:41 UTC, yurii-litvinov requested changes

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/ConnectionTests/ConnetctionTest.cs
> +        const int port = 750;
Первые 1024 порта зарезервированы

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/ConnectionTests/ConnetctionTest.cs
> +        IPAddress ipAdress = IPAddress.Any;
private

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +        /// Creates the new instance of FTPClient, that will work with the choosen stream
ch**o**sen

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/FTPClient/FTPClient.cs
> +            var response = await reader.ReadLineAsync();
Через ReadLineAsync тут вроде читать нельзя, потому что вы рискуете вычитать весь присланный файл, что сделает бесполезной всю буферизацию.

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/FTPClient/UserInterface.cs
> +        public UserInterface(FTPClient fTPClient)
Тут бы тоже имя параметра стоило отстайлгайдить

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/FTPClientTests/FTPClientTests.cs
> +            var fs = new FileStream(sentFilePath, FileMode.Open);
Лучше всё-таки через using var открывать

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/FTPClientTests/FTPClientTests.cs
> +            var recievedFileFs = new FileStream(recievedFilePath, FileMode.Open);
rec**ei**vedFileFs

2020-12-11 17:41 UTC, yurii-litvinov commented on 4.1/FTPServer/ConnectionProvider.cs
> +                        await writer.WriteLineAsync(response.message);
Ага, понятно, почему у Вас Get работает --- Вы пишете перевод строки между размером и данными. В условии не так было :) В коммуникационных протоколах отклонение от ТЗ на один байт часто приводит к тому, что системы вообще не работают вместе --- тут Ваш сервер с большой вероятностью будет несовместим с чужими клиентами (хотя Ваша версия протокола, конечно, разумней)

2021-01-07 12:44 UTC, merged